In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings 
warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset('mpg')

In [4]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [5]:
df.drop("name", axis=1, inplace=True)

In [6]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [8]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [9]:
df.shape

(398, 8)

In [10]:
df.horsepower.median()

np.float64(93.5)

In [11]:
df['horsepower'] = df['horsepower'].fillna(df.horsepower.median())

In [12]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [13]:
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [15]:
df['origin'] = df['origin'].map({"usa": 1, "japan": 2, "europe": 3})

In [16]:
df['origin'].value_counts()

origin
1    249
2     79
3     70
Name: count, dtype: int64

In [17]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin            int64
dtype: object

In [18]:
# seprate into X and y

In [19]:
X = df.drop('mpg', axis=1)
y = df['mpg']

In [22]:
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,3
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1
397,4,119.0,82.0,2720,19.4,82,1

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [26]:
X_test

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
174,6,171.0,97.0,2984,14.5,75,1
359,4,141.0,80.0,3230,20.4,81,3
250,8,318.0,140.0,3735,13.2,78,1
274,5,131.0,103.0,2830,15.9,78,3
283,6,232.0,90.0,3265,18.2,79,1
...,...,...,...,...,...,...,...
382,4,108.0,70.0,2245,16.9,82,2
39,8,400.0,175.0,4464,11.5,71,1
171,4,134.0,96.0,2702,13.5,75,2
271,4,156.0,105.0,2745,16.7,78,1
247,4,85.0,70.0,2070,18.6,78,2

In [27]:
from sklearn.linear_model import LinearRegression

regression_model = LinearRegression()

In [28]:
regression_model

LinearRegression()

In [29]:
regression_model.fit(X_train, y_train)

LinearRegression()

In [30]:
regression_model.coef_

array([-0.31761423,  0.02623748, -0.01827076, -0.00748775,  0.05040673,
        0.84709514,  1.51909584])

In [31]:
for i, col_name in enumerate(X_train.columns):
    print(f"The coefficient for {col_name} is {regression_model.coef_[i]}")

The coefficient for cylinders is -0.3176142302799369
The coefficient for displacement is 0.026237482599078946
The coefficient for horsepower is -0.018270764913124595
The coefficient for weight is -0.007487750398361897
The coefficient for acceleration is 0.0504067346197138
The coefficient for model_year is 0.8470951427061365
The coefficient for origin is 1.5190958387975024

In [33]:
from sklearn.metrics import r2_score

y_pred_linear = regression_model.predict(X_test)
r2_linear = r2_score(y_test, y_pred_linear)
r2_linear

0.8348001123742285

In [34]:
# regularised model
# ridge regression

In [35]:
from sklearn.linear_model import Ridge

ridge_regression_model = Ridge(alpha=0.1)
ridge_regression_model

Ridge(alpha=0.1)

In [36]:
ridge_regression_model.fit(X_train, y_train)

Ridge(alpha=0.1)

In [37]:
for i, col_name in enumerate(X_train.columns):
    print(f"The coefficient for {col_name} is {ridge_regression_model.coef_[i]}")

The coefficient for cylinders is -0.317003210100688
The coefficient for displacement is 0.026213249757983868
The coefficient for horsepower is -0.018263252481448933
The coefficient for weight is -0.007487326050213144
The coefficient for acceleration is 0.05036896947442996
The coefficient for model_year is 0.8470062938903175
The coefficient for origin is 1.5174528285653952

In [40]:
y_pred_ridge = ridge_regression_model.predict(X_test)
r2_ridge = r2_score(y_test, y_pred_ridge)
r2_ridge

0.8348084889168356

In [41]:
from sklearn.linear_model import Lasso

lasso_regression_model = Lasso(alpha=0.5)

In [42]:
lasso_regression_model

Lasso(alpha=0.5)

In [43]:
lasso_regression_model.fit(X_train, y_train)

Lasso(alpha=0.5)

In [44]:
for i, col_name in enumerate(X_train.columns):
    print(f"The coefficient for {col_name} is {lasso_regression_model.coef_[i]}")

The coefficient for cylinders is -0.0
The coefficient for displacement is 0.006208198888300358
The coefficient for horsepower is -0.011058382987169565
The coefficient for weight is -0.0069826731680230885
The coefficient for acceleration is 0.0
The coefficient for model_year is 0.744654952003819
The coefficient for origin is 0.0

In [45]:
y_pred_lasso = lasso_regression_model.predict(X_test)
r2_lasso = r2_score(y_test, y_pred_lasso)
r2_lasso

0.8277934716635555

In [50]:
from sklearn.linear_model import ElasticNet

elasticnet_regression_model = ElasticNet(alpha=1, l1_ratio=0.5)
elasticnet_regression_model

ElasticNet(alpha=1)

In [51]:
elasticnet_regression_model.fit(X_train, y_train)

ElasticNet(alpha=1)

In [52]:
for i, col_name in enumerate(X_train.columns):
    print(f"The coefficient for {col_name} is {elasticnet_regression_model.coef_[i]}")

The coefficient for cylinders is -0.0
The coefficient for displacement is 0.005888869953667563
The coefficient for horsepower is -0.012403874933570126
The coefficient for weight is -0.006934550516257631
The coefficient for acceleration is 0.0
The coefficient for model_year is 0.7133150744603874
The coefficient for origin is 0.0

In [53]:
y_pred_elasticnet = elasticnet_regression_model.predict(X_test)
r2_elasticnet = r2_score(y_test, y_pred_elasticnet)
r2_elasticnet

0.8284840073256804

In [56]:
# regularisation with crossvalidation
from sklearn.linear_model import LassoCV

lasso_cv = LassoCV(cv = 5, verbose=2)

In [57]:
lasso_cv.fit(X_train, y_train)

Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

LassoCV(cv=5, verbose=2)

In [58]:
y_pred = lasso_cv.predict(X_test)
r2_score(y_test, y_pred)

0.8082805983844751

In [59]:
from sklearn.linear_model import RidgeCV
ridge_cv = RidgeCV(cv=5)
ridge_cv.fit(X_train, y_train)

RidgeCV(cv=5)

In [61]:
y_pred = ridge_cv.predict(X_test)
r2_score(y_test, y_pred)

0.8354145247502055

In [62]:
from sklearn.linear_model import ElasticNetCV