In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('IMDB Dataset.csv')

In [4]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
print(df['review'][0])

One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

In [7]:
df = df.sample(10000)

In [8]:
df.shape

(10000, 2)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 5413 to 17295
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [11]:
df['sentiment'].replace({'positive': 1, 'negative': 0}, inplace=True)

C:\Users\prami\AppData\Local\Temp\ipykernel_2692\3188136084.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive': 1, 'negative': 0}, inplace=True)

In [12]:
df

                                                  review  sentiment
5413   On paper this looked like a great concept: Ave...          1
48765  A beautiful film.John Garfield's character is ...          1
18427  Jeremy Northam struggles against a "Total Reca...          0
9425   The first time I had heard of Guest House Pari...          0
12290  Mikio Naruse's examination of the lives of thr...          1
...                                                  ...        ...
46508  I can agree with other comments that there was...          1
6308   I'm totally agree with GarryJohal from Singapo...          1
35289  Watching this again recently, I found it heart...          0
41688  I also made the mistake of thinking that I was...          0
17295  Amongst the standard one liner type action fil...          1

[10000 rows x 2 columns]

In [13]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

'Jeremy Northam struggles against a "Total Recall" clone script and disposable romantic by-play to bring life to a confused character. Lucy Liu graduates her acting from a wooden start to a workman-like finish. You can\'t fail to laugh when viewing her interviews on the DVD when she uses the term "Femme fatal" and "Romance". French film-noir actress she is not and they lack chemistry together.This movie fails, not in the plot or the action sequences but in the lack of attention to detail in the films photography and ham-fisted portrayal of the world of technology surrounding the main protagonists. Little attempt is made to dress the scenery to represent any contiguous filmic landscape or period. Automobiles are very 1990\'s and the architecture barely modern with open plans that hint at a restricted budget rather than conscious set dressing techniques.The technology is positively hilarious. Massive "2001: A Space Odyssey" mainframes fed by man-portable CD-ROM\'s with data collected for some unexplained reason, in spite of the proliferating communications network that even the most un-savvy technologist today would obviously be aware. There is an obvious lack of research done here and given the open-source nature of the cyber-community, research would have cost little more than a bulletin board and personal time.DVD interviews also reveal the original movie name was "Company Man" but this likely ditched in order to cash in on Matrix hype. The "Cypher" title has only the slightest link with the movie. Terry Gilliam would have done wonders with this concept; and completely re-written the Decalogue.This is Tele-movie quality and extremely disappointing for a movie length production. It might have made a good sub-plot for "Alias".'

In [ ]:
def clean_html(text):
    clean = re.compile('<.*?>')