In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings 
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,-,MERCEDES-BENZ,CLK 200,1999,Coupe,Yes,CNG,2.0 Turbo,300000 km,4.0,Manual,Rear,02-Mar,Left wheel,Silver,5
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600 km,4.0,Tiptronic,Front,04-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365 km,4.0,Automatic,Front,04-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258 km,4.0,Automatic,Front,04-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923 km,4.0,Automatic,Front,04-May,Left wheel,White,12

In [4]:
df.columns

Index(['ID', 'Price', 'Levy', 'Manufacturer', 'Model', 'Prod. year',
       'Category', 'Leather interior', 'Fuel type', 'Engine volume', 'Mileage',
       'Cylinders', 'Gear box type', 'Drive wheels', 'Doors', 'Wheel', 'Color',
       'Airbags'],
      dtype='object')

In [5]:
df.dtypes

ID                    int64
Price                 int64
Levy                 object
Manufacturer         object
Model                object
Prod. year            int64
Category             object
Leather interior     object
Fuel type            object
Engine volume        object
Mileage              object
Cylinders           float64
Gear box type        object
Drive wheels         object
Doors                object
Wheel                object
Color                object
Airbags               int64
dtype: object

In [6]:
df.isna().sum()

ID                  0
Price               0
Levy                0
Manufacturer        0
Model               0
Prod. year          0
Category            0
Leather interior    0
Fuel type           0
Engine volume       0
Mileage             0
Cylinders           0
Gear box type       0
Drive wheels        0
Doors               0
Wheel               0
Color               0
Airbags             0
dtype: int64

In [7]:
df.dtypes

ID                    int64
Price                 int64
Levy                 object
Manufacturer         object
Model                object
Prod. year            int64
Category             object
Leather interior     object
Fuel type            object
Engine volume        object
Mileage              object
Cylinders           float64
Gear box type        object
Drive wheels         object
Doors                object
Wheel                object
Color                object
Airbags               int64
dtype: object

In [9]:
df.Levy.unique()

array(['1399', '1018', '-', '862', '446', '891', '761', '751', '394',
       '1053', '1055', '1079', '810', '2386', '1850', '531', '586',
       '1249', '2455', '583', '1537', '1288', '915', '1750', '707',
       '1077', '1486', '1091', '650', '382', '1436', '1194', '503',
       '1017', '1104', '639', '629', '919', '781', '530', '640', '765',
       '777', '779', '934', '769', '645', '1185', '1324', '830', '1187',
       '1111', '760', '642', '1604', '1095', '966', '473', '1138', '1811',
       '988', '917', '1156', '687', '11714', '836', '1347', '2866',
       '1646', '259', '609', '697', '585', '475', '690', '308', '1823',
       '1361', '1273', '924', '584', '2078', '831', '1172', '893', '1872',
       '1885', '1266', '447', '2148', '1730', '730', '289', '502', '333',
       '1325', '247', '879', '1342', '1327', '1598', '1514', '1058',
       '738', '1935', '481', '1522', '1282', '456', '880', '900', '798',
       '1277', '442', '1051', '790', '1292', '1047', '528', '1211',
       '1493', '1793', '574', '930', '1998', '271', '706', '1481', '1677',
       '1661', '1286', '1408', '1090', '595', '1451', '1267', '993',
       '1714', '878', '641', '749', '1511', '603', '353', '877', '1236',
       '1141', '397', '784', '1024', '1357', '1301', '770', '922', '1438',
       '753', '607', '1363', '638', '490', '431', '565', '517', '833',
       '489', '1760', '986', '1841', '1620', '1360', '474', '1099', '978',
       '1624', '1946', '1268', '1307', '696', '649', '666', '2151', '551',
       '800', '971', '1323', '2377', '1845', '1083', '694', '463', '419',
       '345', '1515', '1505', '2056', '1203', '729', '460', '1356', '876',
       '911', '1190', '780', '448', '2410', '1848', '1148', '834', '1275',
       '1028', '1197', '724', '890', '1705', '505', '789', '2959', '518',
       '461', '1719', '2858', '3156', '2225', '2177', '1968', '1888',
       '1308', '2736', '1103', '557', '2195', '843', '1664', '723',
       '4508', '562', '501', '2018', '1076', '1202', '3301', '691',
       '1440', '1869', '1178', '418', '1820', '1413', '488', '1304',
       '363', '2108', '521', '1659', '87', '1411', '1528', '3292', '7058',
       '1578', '627', '874', '1996', '1488', '5679', '1234', '5603',
       '400', '889', '3268', '875', '949', '2265', '441', '742', '425',
       '2476', '2971', '614', '1816', '1375', '1405', '2297', '1062',
       '1113', '420', '2469', '658', '1951', '2670', '2578', '1995',
       '1032', '994', '1011', '2421', '1296', '155', '494', '426', '1086',
       '961', '2236', '1829', '764', '1834', '1054', '617', '1529',
       '2266', '637', '626', '1832', '1016', '2002', '1756', '746',
       '1285', '2690', '1118', '5332', '980', '1807', '970', '1228',
       '1195', '1132', '1768', '1384', '1080', '7063', '1817', '1452',
       '1975', '1368', '702', '1974', '1781', '1036', '944', '663', '364',
       '1539', '1345', '1680', '2209', '741', '1575', '695', '1317',
       '294', '1525', '424', '997', '1473', '1552', '2819', '2188',
       '1668', '3057', '799', '1502', '2606', '552', '1694', '1759',
       '1110', '399', '1470', '1174', '5877', '1474', '1688', '526',
       '686', '5908', '1107', '2070', '1468', '1246', '1685', '556',
       '1533', '1917', '1346', '732', '692', '579', '421', '362', '3505',
       '1855', '2711', '1586', '3739', '681', '1708', '2278', '1701',
       '722', '1482', '928', '827', '832', '527', '604', '173', '1341',
       '3329', '1553', '859', '167', '916', '828', '2082', '1176', '1108',
       '975', '3008', '1516', '2269', '1699', '2073', '1031', '1503',
       '2364', '1030', '1442', '5666', '2715', '1437', '2067', '1426',
       '2908', '1279', '866', '4283', '279', '2658', '3015', '2004',
       '1391', '4736', '748', '1466', '644', '683', '2705', '1297', '731',
       '1252', '2216', '3141', '3273', '1518', '1723', '1588', '972',
       '682', '1094', '668', '175', '967', '402', '3894', '1960', '1599',
       '2000', '2084', '1621', '714', '1109', '3989', '873', '1572',
       '1163', '1991', '1716', '1673', '2562', '2874', '965', '462',
       '605', '1948', '1736', '3518', '2054', '2467', '1681', '1272',
       '1205', '750', '2156', '2566', '115', '524', '3184', '676', '1678',
       '612', '328', '955', '1441', '1675', '3965', '2909', '623', '822',
       '867', '3025', '1993', '792', '636', '4057', '3743', '2337',
       '2570', '2418', '2472', '3910', '1662', '2123', '2628', '3208',
       '2080', '3699', '2913', '864', '2505', '870', '7536', '1924',
       '1671', '1064', '1836', '1866', '4741', '841', '1369', '5681',
       '3112', '1366', '2223', '1198', '1039', '3811', '3571', '1387',
       '1171', '1365', '1531', '1590', '11706', '2308', '4860', '1641',
       '1045', '1901'], dtype=object)

In [13]:
df['Levy'].str.replace('-', "")

0        1399
1        1018
2
3         862
4         446
         ...
19232
19233     831
19234     836
19235    1288
19236     753
Name: Levy, Length: 19237, dtype: object

In [18]:
df['Levy'] = pd.to_numeric(df['Levy'], errors='coerce')

In [19]:
df.dtypes

ID                    int64
Price                 int64
Levy                float64
Manufacturer         object
Model                object
Prod. year            int64
Category             object
Leather interior     object
Fuel type            object
Engine volume        object
Mileage              object
Cylinders           float64
Gear box type        object
Drive wheels         object
Doors                object
Wheel                object
Color                object
Airbags               int64
dtype: object

In [23]:
df.Manufacturer.nunique()

65

In [22]:
df.Model.nunique()

1590

In [24]:
df.drop("Model", axis=1, inplace=True)

In [25]:
df.columns

Index(['ID', 'Price', 'Levy', 'Manufacturer', 'Prod. year', 'Category',
       'Leather interior', 'Fuel type', 'Engine volume', 'Mileage',
       'Cylinders', 'Gear box type', 'Drive wheels', 'Doors', 'Wheel', 'Color',
       'Airbags'],
      dtype='object')

In [26]:
df['Prod. year']

0        2010
1        2011
2        2006
3        2011
4        2014
         ...
19232    1999
19233    2011
19234    2010
19235    2007
19236    2012
Name: Prod. year, Length: 19237, dtype: int64

In [28]:
df.Category.unique()

array(['Jeep', 'Hatchback', 'Sedan', 'Microbus', 'Goods wagon',
       'Universal', 'Coupe', 'Minivan', 'Cabriolet', 'Limousine',
       'Pickup'], dtype=object)

In [29]:
df['Leather interior'].unique()

array(['Yes', 'No'], dtype=object)

In [30]:
df['Fuel type'].unique()

array(['Hybrid', 'Petrol', 'Diesel', 'CNG', 'Plug-in Hybrid', 'LPG',
       'Hydrogen'], dtype=object)

In [31]:
df['Engine volume'].unique()

array(['3.5', '3', '1.3', '2.5', '2', '1.8', '2.4', '4', '1.6', '3.3',
       '2.0 Turbo', '2.2 Turbo', '4.7', '1.5', '4.4', '3.0 Turbo',
       '1.4 Turbo', '3.6', '2.3', '1.5 Turbo', '1.6 Turbo', '2.2',
       '2.3 Turbo', '1.4', '5.5', '2.8 Turbo', '3.2', '3.8', '4.6', '1.2',
       '5', '1.7', '2.9', '0.5', '1.8 Turbo', '2.4 Turbo', '3.5 Turbo',
       '1.9', '2.7', '4.8', '5.3', '0.4', '2.8', '3.2 Turbo', '1.1',
       '2.1', '0.7', '5.4', '1.3 Turbo', '3.7', '1', '2.5 Turbo', '2.6',
       '1.9 Turbo', '4.4 Turbo', '4.7 Turbo', '0.8', '0.2 Turbo', '5.7',
       '4.8 Turbo', '4.6 Turbo', '6.7', '6.2', '1.2 Turbo', '3.4',
       '1.7 Turbo', '6.3 Turbo', '2.7 Turbo', '4.3', '4.2', '2.9 Turbo',
       '0', '4.0 Turbo', '20', '3.6 Turbo', '0.3', '3.7 Turbo', '5.9',
       '5.5 Turbo', '0.2', '2.1 Turbo', '5.6', '6', '0.7 Turbo',
       '0.6 Turbo', '6.8', '4.5', '0.6', '7.3', '0.1', '1.0 Turbo', '6.3',
       '4.5 Turbo', '0.8 Turbo', '4.2 Turbo', '3.1', '5.0 Turbo', '6.4',
       '3.9', '5.7 Turbo', '0.9', '0.4 Turbo', '5.4 Turbo', '0.3 Turbo',
       '5.2', '5.8', '1.1 Turbo'], dtype=object)

In [32]:
df.drop('Engine volume', axis=1, inplace=True)

In [34]:
df['Mileage'].unique()

array(['186005 km', '192000 km', '200000 km', ..., '140607 km',
       '307325 km', '186923 km'], shape=(7687,), dtype=object)

In [35]:
df['Mileage'].str.replace(" km", "")

0        186005
1        192000
2        200000
3        168966
4         91901
          ...
19232    300000
19233    161600
19234    116365
19235     51258
19236    186923
Name: Mileage, Length: 19237, dtype: object

In [36]:
df['Mileage'] = pd.to_numeric(df['Mileage'].str.replace(" km", ""), errors='coerce')

In [37]:
df.Cylinders

0        6.0
1        6.0
2        4.0
3        4.0
4        4.0
        ...
19232    4.0
19233    4.0
19234    4.0
19235    4.0
19236    4.0
Name: Cylinders, Length: 19237, dtype: float64

In [39]:
df['Gear box type'].unique()

array(['Automatic', 'Tiptronic', 'Variator', 'Manual'], dtype=object)

In [40]:
df['Drive wheels'].unique()

array(['4x4', 'Front', 'Rear'], dtype=object)

In [41]:
df['Doors'].unique()

array(['04-May', '02-Mar', '>5'], dtype=object)

In [42]:
df.drop('Doors', axis=1, inplace=True)

In [43]:
df['Wheel'].unique()

array(['Left wheel', 'Right-hand drive'], dtype=object)

In [44]:
df['Color'].unique()

array(['Silver', 'Black', 'White', 'Grey', 'Blue', 'Green', 'Red',
       'Sky blue', 'Orange', 'Yellow', 'Brown', 'Golden', 'Beige',
       'Carnelian red', 'Purple', 'Pink'], dtype=object)

In [45]:
df.columns

Index(['ID', 'Price', 'Levy', 'Manufacturer', 'Prod. year', 'Category',
       'Leather interior', 'Fuel type', 'Mileage', 'Cylinders',
       'Gear box type', 'Drive wheels', 'Wheel', 'Color', 'Airbags'],
      dtype='object')

In [46]:
df['Airbags'].unique()

array([12,  8,  2,  0,  4,  6, 10,  3,  1, 16,  5,  7,  9, 11, 14, 15, 13])

In [47]:
df.dtypes

ID                    int64
Price                 int64
Levy                float64
Manufacturer         object
Prod. year            int64
Category             object
Leather interior     object
Fuel type            object
Mileage               int64
Cylinders           float64
Gear box type        object
Drive wheels         object
Wheel                object
Color                object
Airbags               int64
dtype: object

In [48]:
df = pd.get_dummies(df, dtype=int, drop_first=True)

In [55]:
df.isna().sum()

ID                   0
Price                0
Levy              5819
Prod. year           0
Mileage              0
                  ...
Color_Red            0
Color_Silver         0
Color_Sky blue       0
Color_White          0
Color_Yellow         0
Length: 109, dtype: int64

In [56]:
df.dropna(inplace=True)

In [57]:
X = df.drop('Price', axis=1)
y = df['Price']

In [58]:
X

,ID,Levy,Prod. year,Mileage,Cylinders,Airbags,Manufacturer_ALFA ROMEO,Manufacturer_ASTON MARTIN,Manufacturer_AUDI,Manufacturer_BENTLEY,...,Color_Green,Color_Grey,Color_Orange,Color_Pink,Color_Purple,Color_Red,Color_Silver,Color_Sky blue,Color_White,Color_Yellow
0,45654403,1399.0,2010,186005,6.0,12,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,44731507,1018.0,2011,192000,6.0,8,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,45769185,862.0,2011,168966,4.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,45809263,446.0,2014,91901,4.0,4,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5,45802912,891.0,2016,160931,4.0,4,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19231,45772306,1055.0,2013,107800,6.0,12,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
19233,45778856,831.0,2011,161600,4.0,8,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
19234,45804997,836.0,2010,116365,4.0,4,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
19235,45793526,1288.0,2007,51258,4.0,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19236,45813273,753.0,2012,186923,4.0,12,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [59]:
y

0        13328
1        16621
3         3607
4        11726
5        39493
         ...
19231     5802
19233    15681
19234    26108
19235     5331
19236      470
Name: Price, Length: 13418, dtype: int64

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [63]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [64]:
model.fit(X_train, y_train)

LinearRegression()

In [65]:
y_pred = model.predict(X_test)

In [67]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.26034359330217416