In [1]:
import pandas as pd

In [23]:
df = pd.read_csv('BMI.csv')

In [24]:
df.head()

   Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [25]:
df.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [26]:
df.shape

(500, 4)

In [27]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})
X = df[['Gender', 'Height', 'Weight']]

In [28]:
df.Gender

0      0
1      0
2      1
3      1
4      0
      ..
495    1
496    1
497    1
498    0
499    0
Name: Gender, Length: 500, dtype: int64

In [29]:
vif_data = pd.DataFrame()
vif_data['feature'] = X.columns

vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]
print(vif_data)

  feature        VIF
0  Gender   2.028864
1  Height  11.623103
2  Weight  10.688377

In [31]:
vif_data

  feature        VIF
0  Gender   2.028864
1  Height  11.623103
2  Weight  10.688377

In [32]:
X.values

array([[  0, 174,  96],
       [  0, 189,  87],
       [  1, 185, 110],
       ...,
       [  1, 141, 136],
       [  0, 150,  95],
       [  0, 173, 131]], shape=(500, 3))

In [33]:
# What to do if VIF is high?
# 1. Removing highly correlated features
# 2. Combining variables or using dimensionality reduction techniques