In [108]:
import pandas as pd
import numpy as np

In [109]:
df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [110]:
df.shape

(50000, 2)

In [111]:
df['review'][0]
# "One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. 
# They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was 
# its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, 
# this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, 
# sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname
#  given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the
#  prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, 
# Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings
# and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it 
# goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ 
# doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, 
# but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. 
# Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order 
# and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills 
# or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch 
# with your darker side."

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [112]:
# Problem 1

# Apply all the preprocessing techniques that you think are necessary

# Covert string to lower case
# Remove html tags
# Remove URL
# Remove Punctuation
# Handle Chat Words
# Handle Incorrect text (e.g. Incorrect spelling)
# Handle Stopwords
# Handle emoji
# Tokenization
# Spacy
# Stemming, Lemmitization

In [113]:
# Convert String to lower case
df['review'] = df['review'].str.lower()

In [114]:
# Remove html tags
import re

def remove_html(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [115]:
df['review'] = df['review'].apply(remove_html)

In [116]:
# Remove URL
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [117]:
df['review'] = df['review'].apply(remove_url)

In [118]:
# Remove Punctuation
import string
exclude = string.punctuation
def remove_punctuation(text):
    for char in exclude:
        text = text.replace(char, '')
    return text

# def remove_punc1(text):
#     return text.translate(str.maketrans('', '', exclude))

In [119]:
df['review'] = df['review'].apply(remove_punctuation)

In [120]:
# Handle Chat Words
chat_words = {
    "IMO": "in my opinion",
    "IMHO": "in my humble opinion",
    "LOL": "laugh out loud",
    "LMAO": "laughing my ass off",
    "ROFL": "rolling on the floor laughing",
    "GM": "good morning",
    "GN": "good night",
    "BRB": "be right back",
    "BTW": "by the way",
    "IDK": "i don't know",
    "IDC": "i don't care",
    "TBH": "to be honest",
    "TTYL": "talk to you later",
    "OMG": "oh my god",
    "FYI": "for your information",
    "ASAP": "as soon as possible",
    "GTG": "got to go",
    "TTYS": "talk to you soon",
    "NP": "no problem",
    "TY": "thank you",
    "TYSM": "thank you so much",
    "PLS": "please",
    "PLZ": "please",
    "CU": "see you",
}

def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [121]:
chat_conversion('IMHO he is the best')

'in my humble opinion he is the best'

In [122]:
df['review'] = df['review'].apply(chat_conversion)

In [123]:
# Handle Incorrect text (e.g. Incorrect spelling)
from textblob import TextBlob

In [124]:
incorrect_text = 'ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner.'

textBlb = TextBlob(incorrect_text)
textBlb.correct().string
# blob = TextBlob("Hi Subham")
# print(blob.sentiment)

# textblow library is used for sentiment analysis, spelling correction, 
# tokenization, noun phrase extraction, language translation, part of speech
# tagging,

'certain conditions during several generations are modified in the same manner.'

In [125]:
def correct_spelling(text):
    textBlb = TextBlob(text)
    return textBlb.correct().string

In [126]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production the filming tech...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    im going to have to disagree with the previous...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [127]:
# Handle Stopwords
from nltk.corpus import stopwords

stopword_list = stopwords.words('english')

def remove_stopwords(text):
    return " ".join(
        [word for word in text.split() if word.lower() not in stopword_list]
    )

In [128]:
df['review'] = df['review'].apply(remove_stopwords)

In [129]:
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production filming technique ...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive

In [135]:
# Remove emoji
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [137]:
df['review'] = df['review'].apply(remove_emoji)

In [139]:
import emoji
print(emoji.demojize('😂😂😁😁😁❤️'))

:face_with_tears_of_joy::face_with_tears_of_joy::beaming_face_with_smiling_eyes::beaming_face_with_smiling_eyes::beaming_face_with_smiling_eyes::red_heart:

In [140]:
# Tokenization
# word tokenization
# sentence tokenization
sent1 = 'I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [141]:
sent2 = 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [142]:
sent3 = 'I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [143]:
from nltk.tokenize import word_tokenize, sent_tokenize
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'delhi']

In [144]:
sent_tokenize(sent2)

['I am going to delhi.',
 'I will stay there for 3 days.',
 "Let's hope the trip to be great"]

In [148]:
# Spacy
import spacy
nlp = spacy.load('en_core_web_sm')

In [150]:
# doc1 = nlp(sent5)
# doc2 = nlp(sent6)
# doc3 = nlp(sent7)
doc4 = nlp(sent1)
doc4

I am going to delhi

In [151]:
from nltk.stem.porter import PorterStemmer

In [ ]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join()

In [130]:
# Problem 2

# Find out the number of words in the entire corpus and also the total number of unique words(vocabulary) using just python

In [131]:
# Problem 3

# Apply One Hot Encoding

In [132]:
# Problem 4

# Apply bag words and find the vocabulary also find the times each word has occured

In [133]:
# Problem 5

# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary

In [134]:
# Problem 6

# Apply tf-idf and find out the idf scores of words, also find out the vocabulary.