In [12]:
import torch
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [13]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [14]:
df.shape

(569, 33)

In [15]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [17]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
267,13.590,21.84,87.16,561.0,0.07956,0.08259,0.04072,0.02142,0.1635,0.05859,...,14.80,30.04,97.66,661.5,0.10050,0.17300,0.14530,0.06189,0.2446,0.07024
191,12.770,21.41,82.02,507.4,0.08749,0.06601,0.03112,0.02864,0.1694,0.06287,...,13.75,23.50,89.04,579.5,0.09388,0.08978,0.05186,0.04773,0.2179,0.06871
514,15.050,19.07,97.26,701.9,0.09215,0.08597,0.07486,0.04335,0.1561,0.05915,...,17.58,28.06,113.80,967.0,0.12460,0.21010,0.28660,0.11200,0.2282,0.06954
55,11.520,18.75,73.34,409.0,0.09524,0.05473,0.03036,0.02278,0.1920,0.05907,...,12.84,22.47,81.81,506.2,0.12490,0.08720,0.09076,0.06316,0.3306,0.07036
266,10.600,18.95,69.28,346.4,0.09688,0.11470,0.06387,0.02642,0.1922,0.06491,...,11.88,22.94,78.28,424.8,0.12130,0.25150,0.19160,0.07926,0.2940,0.07587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,20.260,23.03,132.40,1264.0,0.09078,0.13130,0.14650,0.08683,0.2095,0.05649,...,24.22,31.59,156.10,1750.0,0.11900,0.35390,0.40980,0.15730,0.3689,0.08368
528,13.940,13.17,90.31,594.2,0.12480,0.09755,0.10100,0.06615,0.1976,0.06457,...,14.62,15.38,94.52,653.3,0.13940,0.13640,0.15590,0.10150,0.2160,0.07253
367,12.210,18.02,78.31,458.4,0.09231,0.07175,0.04392,0.02027,0.1695,0.05916,...,14.29,24.04,93.85,624.6,0.13680,0.21700,0.24130,0.08829,0.3218,0.07470
158,12.060,12.74,76.84,448.6,0.09311,0.05241,0.01972,0.01963,0.1590,0.05907,...,13.14,18.41,84.08,532.8,0.12750,0.12320,0.08636,0.07025,0.2514,0.07898
359,9.436,18.32,59.82,278.6,0.10090,0.05956,0.02710,0.01406,0.1506,0.06959,...,12.02,25.02,75.79,439.6,0.13330,0.10490,0.11440,0.05052,0.2454,0.08136

In [18]:
y_train

267    B
191    B
514    M
55     B
266    B
      ..
95     M
528    B
367    B
158    B
359    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Label Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [21]:
# Numpy arrays to Pytorch tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [23]:
X_train_tensor.shape

torch.Size([455, 30])

In [24]:
y_train_tensor.shape

torch.Size([455])

In [25]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [26]:
# Important Parameters
learning_rate = 0.1
epochs = 25

In [27]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.9473809477644433
Epoch: 2, Loss: 3.8399973338762714
Epoch: 3, Loss: 3.7299935144332235
Epoch: 4, Loss: 3.6182569568396468
Epoch: 5, Loss: 3.499989171182974
Epoch: 6, Loss: 3.3782062383059115
Epoch: 7, Loss: 3.2528141559508197
Epoch: 8, Loss: 3.1193993011249503
Epoch: 9, Loss: 2.9840548028881404
Epoch: 10, Loss: 2.845322521284435
Epoch: 11, Loss: 2.704593182304158
Epoch: 12, Loss: 2.5584722924530388
Epoch: 13, Loss: 2.408126309872911
Epoch: 14, Loss: 2.252486821372266
Epoch: 15, Loss: 2.0963093889223052
Epoch: 16, Loss: 1.9433285892633292
Epoch: 17, Loss: 1.7916754257276684
Epoch: 18, Loss: 1.6466189555877186
Epoch: 19, Loss: 1.5013465683565703
Epoch: 20, Loss: 1.368431433126457
Epoch: 21, Loss: 1.249547490339967
Epoch: 22, Loss: 1.1460938864798753
Epoch: 23, Loss: 1.0589042624266283
Epoch: 24, Loss: 0.9879489143878926
Epoch: 25, Loss: 0.9321592800584189

In [28]:
model.bias

tensor([-0.1323], dtype=torch.float64, requires_grad=True)

In [29]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5560172200202942